<a href="https://colab.research.google.com/github/Raoina/Spectra-2-Image/blob/main/notebooks/processing_dataset/avg_dataset_moi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [11]:
import pandas as pd

file_path = '/content/drive/MyDrive/DL_FreshCS_train_Multiple_Refs.csv'

try:
  df = pd.read_csv(file_path)
  display(df.head())
except FileNotFoundError:
  print(f"Error: The file '{file_path}' was not found. Please check the path.")
except Exception as e:
  print(f"An error occurred: {e}")

,Scanner ID,Sample ID,Moi,3921.568654,3935.185205,3948.801765,3962.418316,3976.034876,3989.651427,4003.267987,...,7284.857826,7298.474386,7312.090937,7325.707497,7339.324048,7352.940608,7366.557159,7380.173719,7393.790269,7407.406829
0,21060017,Fermented_#_501860,41.00052,18.418626,18.203804,18.029354,17.886841,17.781741,17.733732,17.771375,...,56.518470,57.020849,57.437340,57.788849,58.102487,58.409435,58.729662,59.071404,59.433733,59.812683
1,21060017,Fermented_#_501860,41.00052,17.248456,17.035236,16.867362,16.732971,16.633673,16.585954,16.616447,...,55.072503,55.613406,56.065989,56.449153,56.788504,57.117224,57.460443,57.833951,58.243754,58.688512
2,21060017,Fermented_#_501860,41.00052,18.027023,17.797180,17.610394,17.455654,17.338883,17.282314,17.317228,...,59.389437,59.977661,60.453837,60.840246,61.171445,61.494558,61.846557,62.248987,62.705286,63.204264
3,21060017,Fermented_#_501860,41.00052,18.416102,18.214302,18.051670,17.909884,17.794767,17.734292,17.767441,...,55.554990,56.083525,56.529748,56.898149,57.196891,57.453303,57.700326,57.971976,58.294010,58.677149
4,21060017,Fermented_#_501860,41.00052,17.835506,17.629661,17.468430,17.329677,17.215373,17.150954,17.174831,...,57.914093,58.409864,58.836813,59.218349,59.567331,59.894564,60.209043,60.523319,60.854571,61.222055

In [12]:
# Replace ['column_name_1', 'column_name_2'] with the actual names of the columns you want to drop
columns_to_drop = ['Scanner ID']

# Drop the columns
df.drop(columns=columns_to_drop, axis=1, inplace=True)

# Display the first few rows of the DataFrame after dropping columns
display(df.head())

,Sample ID,Moi,3921.568654,3935.185205,3948.801765,3962.418316,3976.034876,3989.651427,4003.267987,4016.884537,...,7284.857826,7298.474386,7312.090937,7325.707497,7339.324048,7352.940608,7366.557159,7380.173719,7393.790269,7407.406829
0,Fermented_#_501860,41.00052,18.418626,18.203804,18.029354,17.886841,17.781741,17.733732,17.771375,17.923508,...,56.518470,57.020849,57.437340,57.788849,58.102487,58.409435,58.729662,59.071404,59.433733,59.812683
1,Fermented_#_501860,41.00052,17.248456,17.035236,16.867362,16.732971,16.633673,16.585954,16.616447,16.753395,...,55.072503,55.613406,56.065989,56.449153,56.788504,57.117224,57.460443,57.833951,58.243754,58.688512
2,Fermented_#_501860,41.00052,18.027023,17.797180,17.610394,17.455654,17.338883,17.282314,17.317228,17.473581,...,59.389437,59.977661,60.453837,60.840246,61.171445,61.494558,61.846557,62.248987,62.705286,63.204264
3,Fermented_#_501860,41.00052,18.416102,18.214302,18.051670,17.909884,17.794767,17.734292,17.767441,17.929869,...,55.554990,56.083525,56.529748,56.898149,57.196891,57.453303,57.700326,57.971976,58.294010,58.677149
4,Fermented_#_501860,41.00052,17.835506,17.629661,17.468430,17.329677,17.215373,17.150954,17.174831,17.323938,...,57.914093,58.409864,58.836813,59.218349,59.567331,59.894564,60.209043,60.523319,60.854571,61.222055

In [13]:
df.shape

(8163, 259)

In [15]:
# Group by 'Scanner ID' and calculate the mean of other numerical columns
averaged_df = df.groupby('Sample ID').mean()

# Reset the index to turn 'Scanner ID' back into a column
averaged_df.reset_index(inplace=True)

print("DataFrame with averaged values grouped by Scanner ID:")
display(averaged_df.head())

DataFrame with averaged values grouped by Scanner ID:

,Sample ID,Moi,3921.568654,3935.185205,3948.801765,3962.418316,3976.034876,3989.651427,4003.267987,4016.884537,...,7284.857826,7298.474386,7312.090937,7325.707497,7339.324048,7352.940608,7366.557159,7380.173719,7393.790269,7407.406829
0,Fermented_#_480926,60.823286,7.729080,7.622415,7.546208,7.481664,7.423155,7.377601,7.358989,7.381517,...,34.616084,35.288379,35.845357,36.327769,36.777222,37.228529,37.695179,38.173677,38.652607,39.125314
1,Fermented_#_480927,50.485837,9.720940,9.584006,9.485654,9.401768,9.326291,9.270802,9.256881,9.306069,...,42.449703,43.100897,43.648566,44.136925,44.609373,45.097435,45.608556,46.131176,46.646221,47.142563
2,Fermented_#_480929,63.115711,7.551404,7.444440,7.367629,7.300275,7.237015,7.186719,7.165871,7.190576,...,34.907780,35.560699,36.103651,36.578961,37.026430,37.475247,37.932452,38.389652,38.834516,39.264430
3,Fermented_#_480932,65.419594,6.526686,6.434280,6.366056,6.301643,6.235700,6.175937,6.136361,6.129914,...,27.640183,28.252847,28.764077,29.212927,29.634762,30.056096,30.485576,30.919745,31.351121,31.777759
4,Fermented_#_480933,62.917114,6.840954,6.757292,6.697071,6.637614,6.573048,6.512227,6.471038,6.464014,...,28.069196,28.715024,29.254844,29.724470,30.160514,30.594707,31.040131,31.494608,31.948344,32.395361

In [16]:
averaged_df.shape

(784, 259)

In [20]:
# Replace with the actual names of the columns for the first DataFrame
target = ['Sample ID', 'Moi']

# Replace with the actual names of the columns for the second DataFrame
# You can include the remaining columns or a specific subset
# Include 'Scanner ID' in df2 as well
spectra = [col for col in averaged_df.columns if col not in ['Moi']]


df1 = averaged_df[target].copy()
df2 = averaged_df[spectra].copy()

print("First DataFrame (df1) head:")
display(df1.head())

print("\nSecond DataFrame (df2) head:")
display(df2.head())

First DataFrame (df1) head:

            Sample ID        Moi
0  Fermented_#_480926  60.823286
1  Fermented_#_480927  50.485837
2  Fermented_#_480929  63.115711
3  Fermented_#_480932  65.419594
4  Fermented_#_480933  62.917114

Second DataFrame (df2) head:

,Sample ID,3921.568654,3935.185205,3948.801765,3962.418316,3976.034876,3989.651427,4003.267987,4016.884537,4030.501097,...,7284.857826,7298.474386,7312.090937,7325.707497,7339.324048,7352.940608,7366.557159,7380.173719,7393.790269,7407.406829
0,Fermented_#_480926,7.729080,7.622415,7.546208,7.481664,7.423155,7.377601,7.358989,7.381517,7.454154,...,34.616084,35.288379,35.845357,36.327769,36.777222,37.228529,37.695179,38.173677,38.652607,39.125314
1,Fermented_#_480927,9.720940,9.584006,9.485654,9.401768,9.326291,9.270802,9.256881,9.306069,9.431605,...,42.449703,43.100897,43.648566,44.136925,44.609373,45.097435,45.608556,46.131176,46.646221,47.142563
2,Fermented_#_480929,7.551404,7.444440,7.367629,7.300275,7.237015,7.186719,7.165871,7.190576,7.270485,...,34.907780,35.560699,36.103651,36.578961,37.026430,37.475247,37.932452,38.389652,38.834516,39.264430
3,Fermented_#_480932,6.526686,6.434280,6.366056,6.301643,6.235700,6.175937,6.136361,6.129914,6.163474,...,27.640183,28.252847,28.764077,29.212927,29.634762,30.056096,30.485576,30.919745,31.351121,31.777759
4,Fermented_#_480933,6.840954,6.757292,6.697071,6.637614,6.573048,6.512227,6.471038,6.464014,6.498781,...,28.069196,28.715024,29.254844,29.724470,30.160514,30.594707,31.040131,31.494608,31.948344,32.395361

In [21]:
df1.shape

(784, 2)

In [22]:
df2.shape

(784, 258)

In [23]:
# Specify the paths to save the DataFrames in your Google Drive
df1_save_path = '/content/drive/MyDrive/target_siware.csv'
df2_save_path = '/content/drive/MyDrive/spectra_siware.csv'

# Save df1 to a CSV file
df1.to_csv(df1_save_path, index=False)

# Save df2 to a CSV file
df2.to_csv(df2_save_path, index=False)

print(f"df1 saved to: {df1_save_path}")
print(f"df2 saved to: {df2_save_path}")

df1 saved to: /content/drive/MyDrive/target_siware.csv
df2 saved to: /content/drive/MyDrive/spectra_siware.csv